### ISSUE TITLE
Is this tread safe?

### ISSUE THREAD

**Issue by danechitoaie** [maginatics/threadpool#6]
@flandr

What I need to do is have two threads. One of them will keep adding tasks in this thread pool and the other thread will just consume the pool.

Also is there a way to keep listening for tasks? So pool.drain() to listen forever instead of exiting when all tasks are processed? As I will keep adding tasks depending on external events.

**Comment by flandr** [comment]
It wouldn't be a very useful thread pool if it wasn't safe to interact with from multiple threads ;)

I'm not sure if I understand your proposed use, though. You don't need a thread to "consume the pool"; the pool itself is composed of worker threads that consume the tasks that you add via the `execute` or `schedule` interfaces. If you instantiate a threadpool with a maximum worker count of one then it implements the scenario you've described: one worker thread will execute all tasks enqueued via `execute` in sequential order.

The workers listen for tasks until the pool is destroyed; the `drain` method merely waits until all tasks added prior to its invocation have completed.

**Comment by danechitoaie** [comment]
Oh, make sense now. Sorry if my questions was not clear, I'm new to C++ so maybe I didn't asked the right things the right way.

Basically I'm looking to use this in combination with a filesystem watch library that will trigger an event each time a file has changed on disk in some folders. When that happens I just need to execute/queue a task with one param being the file path that was changed. For some reason I was under the impression that only when calling drain the execution of the tasks starts. Makes more sense that `drain` just waits.

I think it's clear now. Thank you.
